
heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running memcached.

parameters:

  image:
    label: Server Image
    description: Server Image
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin)
      description: Must be a supported operating system.

  flavor:
    label: Server Size
    description: Rackspace Cloud Server flavor
    type: string
    default: 1 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 512MB Standard Instance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  server_hostname:
    label: Hostname
    description: Hostname for the server.
    type: string
    default: memcache

  memory_percentage:
    label: Allowed Memory Size
    description: Percentage of memory memcached is allowed to use
    type: number
    default: 60

  memcached_port:
    label: Memcached Port
    description: Port memcached will listen on
    type: number
    default: 11211

resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  memcached_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }

  memcached_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: memcached_server
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [memcached_server, accessIPv4] }
      Berksfile: |
        site :opscode

        cookbook 'apt'
        cookbook 'memcached'
        cookbook 'rax-memcached',
          :git => 'https://github.com/JasonBoyles/rax-memcached.git'
        cookbook 'rax-firewall',
          :git => 'https://github.com/brint/rax-firewall-cookbook.git'
      node:
        rax_memcached:
          mem_percent: { get_param: memory_percentage }
        memcached:
          port: { get_param: memcached_port }
        run_list: ["recipe[apt]",
                   "recipe[rax-memcached::firewall]",
                   "recipe[rax-memcached::default]"]

outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }

  server_ip:
    value: { get_attr: [memcached_server, accessIPv4] }

  memcached_port:
    value: { get_param: memcached_port }
